/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quic_ffmpegquic_Test */

#ifndef _Included_com_quic_ffmpegquic_Test
#define _Included_com_quic_ffmpegquic_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quic_ffmpegquic_Test
 * Method:    test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_quic_ffmpegquic_Test_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
